# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3.3'
services:
  db:
    container_name: mysqldb
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mysql@1234
      - MYSQL_DATABASE=cubic300_db
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - f:/data/mysql:/data/mysql
    ports:
      - 2012:3306
      
  cubicbank100:
    container_name: cubicbank100api
    image: cubicbank100-image
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
   
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/cubic300_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}  

    ports:
      - 8087:8080
    volumes:
      - f:/data/spring-boot-app:/data/spring-boot-app